-- CREATE TABLE "issue"("id" INTEGER PRIMARY KEY,"author" INTEGER NOT NULL REFERENCES "user" ON DELETE RESTRICT ON UPDATE RESTRICT,"open" BOOLEAN NOT NULL,"title" VARCHAR NOT NULL,"approval" REAL NOT NULL,"comment_num" INTEGER NOT NULL,"created" TIMESTAMP NOT NULL,"cur_version" INTEGER NULL REFERENCES "issue_version" ON DELETE RESTRICT ON UPDATE RESTRICT)

ALTER TABLE issue ADD approval    REAL    NOT NULL DEFAULT 0;
ALTER TABLE issue ADD comment_num INTEGER NOT NULL DEFAULT 0;
