resolver: lts-20.26

packages:
  - oneshot
  - stellar-horizon
  - veche-web
  - withcallstack
  - yesod-form-bootstrap5

extra-deps:
  # stellar-sdk
    - github: TomMD/cipher-aes128
      commit: 4f30d283de04a65cde5aab4500dd7d7b409602d5
    - DRBG-0.5.5
  # veche-web
    - github: cblp/haskell-telegram-api
      commit: ad5876d510e6d934725b7405e12e68bb8ae5eee9
      # https://github.com/klappvisor/haskell-telegram-api/pull/133
  # yesod-auth-stellar
    - github: cblp/haskell-stellar-sdk
      commit: 7e1c20903b5ed88681ac924e65ed67d36667e074
      # https://github.com/teequoo/haskell-stellar-sdk/pull/2
