resolver: lts-19.25

packages:
  - stellar-horizon
  - veche-web
  - yesod-auth-stellar
  - yesod-form-bootstrap5

extra-deps:
  # stellar-horizon:exe
    - github: cblp/servant-cli
      commit: 929da900e2a6526450e846e7182b3df6bc989209
      # https://github.com/mstksg/servant-cli/pull/3
  # stellar-sdk
    - DRBG-0.5.5
  # veche-web
    - yesod-form-1.7.3
    - github: cblp/haskell-telegram-api
      commit: 8c369af6a560cb3cf842068ab7c291dea8d5e2b8
  # yesod-auth-stellar
    - github: cblp/haskell-stellar-sdk
      commit: 370f67c59b3102fadd3772217c7e9681d4c4404c
