DROP TABLE "notification";

CREATE TABLE "event"(
    "id" INTEGER PRIMARY KEY,
    "type" VARCHAR NOT NULL,
    "time" TIMESTAMP NOT NULL,
    "delivered" BOOLEAN NOT NULL,
    "issue" INTEGER NULL
        REFERENCES "issue" ON DELETE RESTRICT ON UPDATE RESTRICT,
    "comment" INTEGER NULL
        REFERENCES "comment" ON DELETE RESTRICT ON UPDATE RESTRICT
);
