CREATE TABLE attachment_tx
    ( id INTEGER PRIMARY KEY
    , issue INTEGER NOT NULL
        REFERENCES issue ON DELETE RESTRICT ON UPDATE RESTRICT
    , code BLOB NOT NULL
    , updated TIMESTAMP NOT NULL
    , updated_by INTEGER NOT NULL
        REFERENCES user ON DELETE RESTRICT ON UPDATE RESTRICT
    );
