DROP TABLE event;

ALTER TABLE comment ADD COLUMN event_delivered BOOLEAN   NOT NULL DEFAULT FALSE;

ALTER TABLE issue   ADD COLUMN event_delivered BOOLEAN   NOT NULL DEFAULT FALSE;

ALTER TABLE request ADD COLUMN event_delivered BOOLEAN   NOT NULL DEFAULT FALSE;
ALTER TABLE request ADD COLUMN created         TIMESTAMP NOT NULL DEFAULT 0;
ALTER TABLE request DROP COLUMN delivered;
UPDATE request SET created = CURRENT_TIMESTAMP WHERE created = 0;
