# navbar
About: About
Dashboard: Dashboard
Forums: Forums
Issues: Issues
Profile: Profile
LogIn: Log in
LogOut: Log out

# alerts
LogInToComment: Log in to see full publication and add comments

# other
Unauthorized: You must log in to access this page

# log in
ViaStellar: Via Stellar
ViaTelegram: Via Telegram (existing Veche accounts only)
CreateAccountOrLogIn: Create account or log in

# about
Veche: Veche
AboutDescription: This is a tool for organizing work in the Montelibero community.

# forums
Public: Public
OnlyFor: Only for

# forum
Open: open
Closed: closed
NewIssue: New issue

# message new & edit
IssueForum: Forum
IssueTitle: Title
IssueMessage: Message
IssuePriceOffer: Price offer
IssueContacts: Contacts
IssuePoll: Poll
IssuePublish: Publish

# issue
IssueOpen: Open
IssueClosed: Closed
IssueEdit: Edit
IssueClose: Close
IssueReopen: Reopen
IssueReply: Reply
IssueRequestInfo: Request info
IssueComment: Комментарий
IssueProvideInfo: Provide info for
IssueRequestInfoFrom: Request info from
IssueRequestStartTyping: Start typing a user name or an address
IssueAddComment: Add comment

# poll type
PollDisabled: Disabled
PollMtlShare: Proportionally to MTL share
PollMtlSignerWeight: Proportionally to Stellar signer weight
