# navbar
About: About
Dashboard: Dashboard
Forums: Forums
Issues: Issues
Profile: Profile
LogIn: Log in
LogOut: Log out

# alerts
LogInToComment: Log in to see full publication and add comments

# other
Unauthorized: You must log in to access this page

# log in
AuthnViaStellar: Via Stellar
AuthnViaTelegram: Via Telegram (existing Veche accounts only)
CreateAccountOrLogIn: Create account or log in
LogInViaKeybase: Log in via Keybase
LogInViaMMWB: Log in via @MyMtlWalletBot
LogInViaStellarLaboratory: Log in via Stellar Laboratory
LabelStellarPublicAddress: Stellar public key (also known as address, starts with G):
TelegramIsBound: I've bound Telegram account

# log in via Stellar Laboratory and Keybase
AuthnStellarIntro: For the purpose of authentications in Veche a special "request" transaction is made.
AuthnStellarIntroRun: Run this command in your command line to sign this transaction, but do not submit it, instead, paste the code below:
AuthnStellarIntroLab: Sign this transaction, but do not submit it, instead, paste the code below:
AuthnStellarDesc: This is an almost empty, intentionally invalid transaction. It has zero fee and zero sequence number, specifically to make sure it cannot be sent to the real network.
AuthnStellarCopyCommand: Copy the command
AuthnStellarCopyTx: Copy the transaction
AuthnStellarViewInLab: View in Lab
AuthnStellarSignInLab: Sign in Lab
AuthnStellarRun: Start Keybase and run the command on your computer
AuthnStellar3PasteSigned: 3. Paste the signed piece here:

# about
Veche: Veche
AboutDescription: This is a tool for organizing work in the Montelibero community.

# dashboard
InfoRequests: Information requests
Issue: Issue

# forums
Public: Public
OnlyFor: Only for

# forum
Open: open
Closed: closed
NewIssue: New issue

# message new & edit
IssueForum: Forum
IssueTitle: Title
IssueMessage: Message
IssuePriceOffer: Price offer
IssueContacts: Contacts
IssuePoll: Poll
IssuePublish: Publish

# issue
IssueOpen: Open
IssueClosed: Closed
IssueEdit: Edit
IssueClose: Close
IssueReopen: Reopen
IssueReply: Reply
IssueRequestInfo: Request info
IssueComment: Комментарий
CommentProvideInfo: Provide info for
IssueRequestInfoFrom: Request info from
IssueRequestStartTyping: Start typing a user name or an address
IssueAddComment: Add comment

# poll type
PollDisabled: Disabled
PollByAmountOfFcm: Proportionally to FCM share
PollByAmountOfVeche: Proportionally to VECHE share
PollMtlShare: Proportionally to MTL share
PollMtlSignerWeight: Proportionally to Stellar signer weight

# telegram bot
TelegramBotHelp site@Text: This bot is a part of the Veche service #{site}. Available commands: /help
TelegramBotLoginButton: Log in to the website
TelegramBotNotUnderstood: I didn't understand your message. Try /help
TelegramBotSettingsButton: Account settings

# user profile
UserProfile: User profile
Name: Name
Save: Save
Cancel: Cancel
StellarAddress: Stellar Address
Roles: Roles
Notifications: Notifications
Event: Event
NewDiscussion: A new discussion is started
SomebodyReplied: Somebody replied to you
SomebodyRequested: Somebody requested you to comment
ConnectTelegramNotifications: Connect Telegram to enable notifications
