# navbar
About: About
Dashboard: Dashboard
Forums: Forums
Issues: Issues
Profile: Profile
LogIn: Log in
LogOut: Log out

# alerts
LogInToComment: Log in to see full publication and add comments

# other
Unauthorized: You must log in to access this page

# log in
AuthnViaStellar: Via Stellar
AuthnViaTelegram: Via Telegram (existing Veche accounts only)
CreateAccountOrLogIn: Create account or log in

# about
Veche: Veche
AboutDescription: This is a tool for organizing work in the Montelibero community.

# dashboard
InfoRequests: Information requests
Issue: Issue

# forums
Public: Public
OnlyFor: Only for

# forum
Open: open
Closed: closed
NewIssue: New issue

# message new & edit
IssueForum: Forum
IssueTitle: Title
IssueMessage: Message
IssuePriceOffer: Price offer
IssueContacts: Contacts
IssuePoll: Poll
IssuePublish: Publish

# issue
IssueOpen: Open
IssueClosed: Closed
IssueEdit: Edit
IssueClose: Close
IssueReopen: Reopen
IssueReply: Reply
IssueRequestInfo: Request info
IssueComment: Комментарий
CommentProvideInfo: Provide info for
IssueRequestInfoFrom: Request info from
IssueRequestStartTyping: Start typing a user name or an address
IssueAddComment: Add comment

# poll type
PollDisabled: Disabled
PollMtlShare: Proportionally to MTL share
PollMtlSignerWeight: Proportionally to Stellar signer weight

# telegram bot
TelegramBotHelp site@Text: This bot is a part of the Veche service #{site}. Available commands: /help
TelegramBotLoginButton: Log in to the website
TelegramBotNotUnderstood: I didn't understand your message. Try /help

# user profile
UserProfile: User profile
Name: Name
Save: Save
Cancel: Cancel
StellarAddress: Stellar Address
Roles: Roles
Notifications: Notifications
Event: Event
NewDiscussion: A new discussion is started
SomebodyReplied: Somebody replied to you
SomebodyRequested: Somebody requested you to comment
ConnectTelegramNotifications: Connect Telegram to enable notifications
