# navbar
About: О нас
Dashboard: Важное
Forums: Форумы
Issues: Обсуждения
Profile: Профиль
LogIn: Вход
LogOut: Выход

# alerts
LogInToComment: Войдите на сайт, и вы сможете читать публикации полностью и оставлять комментарии

# other
Unauthorized: Для получения доступа к странице требуется войти

# log in
AuthnViaStellar: Через Stellar
AuthnViaTelegram: Через Telegram (только если уже есть аккаунт на Вече)
CreateAccountOrLogIn: Создать аккаунт или войти

# about
Veche: Вече
AboutDescription: Это инструмент для организации работы в сообществе Монтелиберо.

# dashboard
InfoRequests: Запросы информации
Issue: Задача

# forums
Public: Публичный
OnlyFor: Только для

# forum
Open: открыто
Closed: закрыто
NewIssue: Новая задача

# message new & edit
IssueForum: Форум
IssueTitle: Заголовок
IssueMessage: Сообщение
IssuePriceOffer: Предлагаемая цена
IssueContacts: Контакты
IssuePoll: Голосование
IssuePublish: Опубликовать

# issue
IssueOpen: Открыта
IssueClosed: Закрыта
IssueEdit: Редактировать
IssueClose: Закрыть
IssueReopen: Открыть
IssueReply: Ответить
IssueComment: Комментарий
CommentProvideInfo: Информация предоставлена для
IssueRequestInfoFrom: Запросить информацию от
IssueRequestStartTyping: Начните писать имя пользователя или адрес
IssueAddComment: Добавить комментарий

# poll type
PollDisabled: Выключено
PollMtlShare: Пропорционально количеству MTL
PollMtlSignerWeight: Пропорционально весу подписи Stella

# telegram bot
TelegramBotHelp site@Text: Этот бот — часть Веча #{site}. Команды: /help
TelegramBotNotUnderstood: Ничего не понял. Попробуйте /help

# user profile
UserProfile: Профиль пользователя
Name: Имя
Save: Cохранить
Cancel: Отмена
StellarAddress: Адрес Stellar
Roles: Роли
Notifications: Уведомления
Event: Событие
NewDiscussion: Начато новое обсуждение
SomebodyReplied: Кто-то ответил вам
SomebodyRequested: Кто-то запросил у вас комментарий
ConnectTelegramNotifications: Подключите Telegram, чтобы включить уведомления
