# authentication
AuthnViaStellar: Через Stellar
AuthnViaTelegram: Через Telegram (только если уже есть аккаунт на Вече)

# comment
CommentProvideInfo: Информация предоставлена для

# issue
IssueClose: Закрыть
IssueReopen: Открыть

# navbar
Dashboard: Главная
Forums: Форумы
Issues: Обсуждения
Profile: Профиль
LogIn: Вход
LogOut: Выход

# alerts
LogInToComment: Войдите на сайт, и вы сможете читать публикации полностью и оставлять комментарии

# other
Unauthorized: Для получения доступа к странице требуется войти
