# navbar
About: О нас
Dashboard: Главная
Forums: Форумы
Issues: Обсуждения
Profile: Профиль
LogIn: Вход
LogOut: Выход

# alerts
LogInToComment: Войдите на сайт, и вы сможете читать публикации полностью и оставлять комментарии

# other
Unauthorized: Для получения доступа к странице требуется войти

# log in
ViaStellar: Через Stellar
ViaTelegram: Через Telegram (только существующие аккаунты Вече)
CreateAccountOrLogIn: Создать аккаунт или войти

# about
Veche: Вече
AboutDescription: Это инструмент для организации работы в сообществе Монтелиберо.

# dashboard
InfoRequests: Запросы информации
Issue: Задача

# forums
Public: Публичный
OnlyFor: Только для

# forum
Open: открыто
Closed: закрыто
NewIssue: Новая задача

# message new & edit
IssueForum: Форум
IssueTitle: Заголовок
IssueMessage: Сообщение
IssuePriceOffer: Предлагаемая цена
IssueContacts: Контакты
IssuePoll: Голосование
IssuePublish: Опубликовать

# issue
IssueOpen: Открыта
IssueClosed: Закрыта
IssueEdit: Редактировать
IssueClose: Закрыть
IssueReopen: Открыть
IssueReply: Ответить
IssueRequestInfo: Запросить информацию
IssueComment: Комментарий
IssueProvideInfo: Предоставить информацию для
IssueRequestInfoFrom: Запросить информацию от
IssueRequestStartTyping: Начните писать имя пользователя или адрес
IssueAddComment: Добавить комментарий

# poll type
PollDisabled: Выключено
PollMtlShare: Пропорционально количеству MTL
PollMtlSignerWeight: Пропорционально весу подписи Stellar